### ISSUE TITLE
Indicate which reserved cards are unavailable

### ISSUE THREAD

**Issue by spencerjanssen** [spencerjanssen/rotothopter#33]

**Comment by andyrut** [comment]
Are reserved cards that are already picked supposed to have strikethrough styling? This doesn't seem to be the case, at least for the attached example.

![screen shot 2018-03-09 at 9 12 28 pm](https://user-images.githubusercontent.com/12550071/37237819-c8b3a6be-23de-11e8-93d5-23c9ce187582.png)

**Comment by spencerjanssen** [comment]
See #54
